package com.ramjo.spring_security_demo.Spring_Security_Demo.service;

import java.util.ArrayList;
import java.util.List;
import com.ramjo.spring_security_demo.Spring_Security_Demo.model.Student;
import com.ramjo.spring_security_demo.Spring_Security_Demo.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {
    @Autowired
    private StudentRepository studentRepository;

    public List<Student> getStudents(){
        return studentRepository.findAll();
    }

    public void addStudent(Student student) {
        //student rollno is autogenerated so giving it in Request Json will threw 500 Error
        studentRepository.save(student);
    }
}
