package com.ramjo.spring_security_demo.Spring_Security_Demo.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import com.ramjo.spring_security_demo.Spring_Security_Demo.model.Student;
import com.ramjo.spring_security_demo.Spring_Security_Demo.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {
    @Autowired
    private StudentRepository studentRepository;

    public List<Student> getStudents(){
        return studentRepository.findAll();
    }

    public Student addStudent(Student student) {
        //student rollno is autogenerated so giving it in Request Json will threw 500 Error
        return studentRepository.save(student);
    }

    public Student updateStudent(Long id, Student student){
        Student existingStudent = studentRepository.findById(id).orElseThrow(() -> new RuntimeException("Student Not Found"));
        existingStudent.setFirstname(student.getFirstname());
        existingStudent.setLastname(student.getLastname());
        return studentRepository.save(existingStudent);
    }
}
